inherit_gem:
  rubocop-legion: config/lex.yml
AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  SuggestExtensions: false

Style/RedundantConstantBase:
  Enabled: false

Layout/LineLength:
  Max: 160
  Exclude:
    - 'Gemfile'

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: space

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
Metrics/ClassLength:
  Max: 1500

Metrics/ModuleLength:
  Max: 1500
Metrics/MethodLength:
  Max: 100
Metrics/AbcSize:
  Max: 80
Metrics/CyclomaticComplexity:
  Max: 25
Metrics/PerceivedComplexity:
  Max: 25
Style/Documentation:
  Enabled: false
Style/SymbolArray:
  Enabled: true
Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always
Style/ModuleFunction:
  Enabled: false
